input:
  path: "input/拆分模版4.28.xlsx"
  sheet:
    source:
      name: "工资"
      columns:
        employee_id: "工号"
        project_id: "费用所属中心"
        project_category: "费用类别"
        project_hours: "实际出勤"
    reference:
      name: "研发人员工时表"
      columns:
        employee_id: "工号"
        project_id: "费用所属中心"
        project_category: "费用类别"
        project_hours: "实际出勤"
  splitting_columns:
  - "基本工资"
  - "岗位工资"
  - "转正/异动基本岗位差额"
  - "转正/异动绩效差额"
  - "转正/异动业绩差额"
  - "转正/异动差额小计"
  - "病假扣款基本岗位"
  - "病假扣款绩效"
  - "病假扣款业绩"
  - "病假扣款小计"
  - "事假扣款-基本岗位"
  - "事假扣款-绩效"
  - "事假扣款-业绩"
  - "事假扣款小计"
  - "旷工扣款-基本岗位"
  - "旷工扣款-绩效"
  - "旷工扣款-业绩"
  - "旷工扣款小计"
  - "迟到扣款"
  - "绩效额外奖惩额"
  - "绩效获取金额"
  - "绩效增扣金额小计"
  - "加班工资"
  - "福利前工资合计"
  - "司龄工资"
  - "用餐补助"
  - "交通补助"
  - "通讯补助"
  - "取暖/防暑补贴"
  - "节日福利"
  - "电脑补贴"
  - "差旅补助"
  - "保密津贴"
  - "保密奖惩"
  - "独生子女奖励"
  - "董监高津贴"
  - "税前其他"
  - "税前应发工资总额"
  - "税前应发工资总额(不含差补)"
  - "税前应发工资总额(不含社保)"
  - "No.1税前应发工资总额(不含社保)"
  - "No.2税前应发工资总额(不含社保)"
  - "代缴个人养老"
  - "代缴个人医疗"
  - "代缴个人失业"
  - "代缴个人公积金"
  - "三险一金"
  - "本年应税工资累计"
  - "本年个税累计"
  - "本年已缴金额"
  - "本月应缴个税"
  - "No.1本月应缴个税"
  - "No.2本月应缴个税"
  - "商业保险"
  - "门禁卡"
  - "ETC费用"
  - "手机押金"
  - "话费个人承担金额"
  - "税后其他"
  - "实发工资"
  - "No.1实发工资"
  - "No.2实发工资"
  - "公司养老保险金额"
  - "公司失业保险金额"
  - "公司工伤保险金额"
  - "公司生育保险金额"
  - "公司医疗保险金额"
  - "公司公积金金额"
  - "公司残保金金额"
  - "服务费"
  - "公司五险一金合计"
  - "公司商业保险金额"
output:
  path: "output/工资拆分.xlsx"
  sheet:
    result:
      name: "工资拆分"
