input:
  path: "input/项目成本.xlsx"  
  sheet:
    source:
      name: "工资"
      columns:
        employee_id: "工号"
        project_id: "费用所属中心"
        project_category: "费用类别"
        project_hours: "实际出勤"
output:
  path: "output/项目成本拆分.xlsx"
  sheet:
    result:
      name: "工资拆分"
